### PR TITLE
patch boot.sh to correctly support bash string comparison

### PR DESCRIPTION
**Pull request by gchevalley**
`if [[ "$?" == "0" ]]; then` is a bash functionality

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
What problem did you find when running this container? Works fine for me as it is.

**Comment by gchevalley** [comment]
when I self-execute the script, I get `./boot.sh: 6: ./boot.sh: [[: not found`

**Comment by miguelgrinberg** [comment]
I'll look into it, I suspect the Alpine Linux image provides `sh` as an alias to `bash`, and that is why it works there. In that case I will make this change.

**Comment by miguelgrinberg** [comment]
The container image for Alpine Linux does not have bash, unfortunately, so your change will break support for Docker, so unfortunately I can't accept this PR.

The shell that comes with Alpine Linux is part of the BusyBox suite of lightweight Unix commands. Busybox and many other systems that use this shell call it `sh`, but it isn't the old original one, it is a compatible variant called `ash`.

I tested the script on my Mac's `sh` shell, and while I have no idea if it is `ash` or something else, it does accept the `[[` and `]]` in conditionals.

What platform are you using? Maybe there is a way to adapt this script to run on older versions of sh like the one you are using?

**Comment by gchevalley** [comment]
Thanks for all theses details, very instructive. I am currently developing and testing on Ubuntu 18.04 and I will deploy with docker images based on python:3-alpine

**Pull request closed without merging**
